# Site settings
title: Ranbytes - Those Thoughts
email: Mike 
description: > # this means to ignore newlines until "baseurl:"
  Random bits-n-bytes that appears in the ether.  Let them manifest and 
	become the start of something wonderful.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mikeclee.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
